import { Product } from './product';

//import { ProductComponent } from '../../products-components/service/product-component';

export const PRODUCTS: Product[] = [{
  'id': 1,
  'name': 'Wiley',
  'description': 'Bertomieu',
  'creation': '27/08/2012',
  'death': null,
  'components': []
}, {
  'id': 2,
  'name': 'Stafford',
  'description': 'Reasce',
  'creation': '02/03/2013',
  'death': null,
  'components': []
}, {
  'id': 3,
  'name': 'Merle',
  'description': 'Jobson',
  'creation': '03/11/2016',
  'death': null,
  'components': []
}, {
  'id': 4,
  'name': 'Gerladina',
  'description': 'Kemmett',
  'creation': '09/06/2016',
  'death': '01/01/2017',
  'components': []
}]
/*
, {
  'id': 5,
  'name': 'Jodie',
  'description': 'Simpole',
  'creation': 'jsimpole4@abc.net.au',
  'death': null
}, {
  'id': 6,
  'name': 'Cherey',
  'description': 'Goodge',
  'creation': 'cgoodge5@51.la',
  'death': 'Female'
}, {
  'id': 7,
  'name': 'Reinaldo',
  'description': 'Gauler',
  'creation': 'rgauler6@buzzfeed.com',
  'death': 'Male'
}, {
  'id': 8,
  'name': 'Torr',
  'description': 'Mitroshinov',
  'creation': 'tmitroshinov7@topsy.com',
  'death': 'Male'
}, {
  'id': 9,
  'name': 'Lexie',
  'description': 'Nilles',
  'creation': 'lnilles8@discuz.net',
  'death': 'Female'
}, {
  'id': 10,
  'name': 'Normy',
  'description': 'Hold',
  'creation': 'nhold9@earthlink.net',
  'death': 'Male'
}, {
  'id': 11,
  'name': 'Judy',
  'description': 'Leaney',
  'creation': 'jleaneya@last.fm',
  'death': null
}, {
  'id': 12,
  'name': 'Eduard',
  'description': 'Lumsdon',
  'creation': 'elumsdonb@zdnet.com',
  'death': 'Male'
}, {
  'id': 13,
  'name': 'Zorine',
  'description': 'Clementi',
  'creation': 'zclementic@blogspot.com',
  'death': 'Female'
}, {
  'id': 14,
  'name': 'Sigismundo',
  'description': 'Marjoram',
  'creation': 'smarjoramd@wunderground.com',
  'death': 'Male'
}, {
  'id': 15,
  'name': 'Felecia',
  'description': 'Heathcott',
  'creation': 'fheathcotte@geocities.com',
  'death': 'Female'
}];*/